### ISSUE TITLE
Dar soporte a las fases del procesado en DevelopmentPlatform

### ISSUE THREAD

**Issue by TaniaHM** [ASG-UBU/GESPRO_GESTIONTAREAS#10]
Permitir visualizar y parametrizar cada una de las distintas fases del procesado (preprocesado, background subtraction, postprocesado...) en la DevelopmentPlatform desarrollada en Java.

**Comment by ASG-UBU** [comment]
Plataforma desarrollada. Catacterísticas:

Cargar vídeo con FileChooser.
Reproductor de vídeo con controles.
Una pestaña por fase con controles de los parámetros de los diferentes algoritmos.
Permite realizar modificaciones de los parámetros en tiempo real.
