### ISSUE TITLE
Postprocesado imagen

### ISSUE THREAD

**Issue by ASG-UBU** [ASG-UBU/GESPRO_GESTIONTAREAS#8]
Investigar técnicas de postprocesado de la imagen después de aplicar la extracción del fondo para mejorar sus resultados.

http://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.html

**Comment by ASG-UBU** [comment]
Descartados:

BackgroundSubtractorKNN descartado por tener tiempo de ejecución elevados (de media 25ms).
Diferencia de frames: descartado por detectar las abejas por duplicado.
Se consideran para parametrización:

accumulateWeighted
BackgroundSubtractorMOG2

**Comment by TaniaHM** [comment]
Se mejoran los resultados realizando los siguientes pasos.

    Dilate
    Erode

Ambos han sido implementados en la DevelopmentPlatform.
