### ISSUE TITLE
Elegir el mejor algoritmo de BS 

### ISSUE THREAD

**Issue by TaniaHM** [ASG-UBU/GESPRO_GESTIONTAREAS#9]
De los algoritmos implementados en el prototipo, realizar una comparativa con varias parametrizaciones para ver cual nos provee mejores resultados.

**Comment by ASG-UBU** [comment]
Se mejoran los resultados realizando los siguientes pasos.

Dilate
Erode
Ambos han sido implementados en la DevelopmentPlatform.
